name: "Build 🔨"

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches: [ main ]

jobs:
  build:
    name: "Build 🔨"
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        scheme:
          - "Swiftfin"

    runs-on: macos-13

    steps:    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SwiftGen
        run: curl -Lo /tmp/swiftgen.rb https://raw.githubusercontent.com/iMichka/homebrew-core/17ae00b4bf1640cc544eae5f6eec03775c09420b/Formula/swiftgen.rb && brew install /tmp/swiftgen.rb && rm /tmp/swiftgen.rb

      - name: Cache Carthage
        uses: actions/cache@v4
        id: carthage-cache
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: ${{ runner.os }}-carthage-

      - name: Update Carthage
        run: carthage update --use-xcframeworks --cache-builds

      - name: Cache Swift packages
        uses: actions/cache@v4
        with:
          path: PackageCache
          key: ${{ runner.os }}-${{ matrix.scheme }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-${{ matrix.scheme }}-spm-

      - name: Build
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 60
          command: |
            xcodebuild build -project "Swiftfin.xcodeproj" \
            -scheme "${{ matrix.scheme }}" \
            -configuration Release \
            -clonedSourcePackagesDirPath PackageCache \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            BUILD_DIR=${{ github.workspace }}/xcodebuild
            
            cd ${{ github.workspace }}/xcodebuild/Release-iphoneos/
            mkdir ./Payload
            cp -r ./Swiftfin\ iOS.app ./Payload/Swiftfin.app
            zip -r9 ./Swiftfin.ipa Payload
            
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Swiftfin
          path: ${{ github.workspace }}/xcodebuild/Release-iphoneos/Swiftfin.ipa
